Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/oracle-java-8-centos7"
    #test01.vm.box = "/home/jeqo/boxes/jeqo/centos-7/centos-7.box"

    test01.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
